name: Build and test

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        SCALA_VERSION: [ 2.12.17, 2.13.10 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: generate and test, Scala ${{ matrix.SCALA_VERSION }}
        # This runs the template with the default parameters, and runs test within the templated app.
        run: sbt ++${{ matrix.SCALA_VERSION }} -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test docs/paradox