name: Build and test

on:
  pull_request:
  push:
    branches:
      - 2.*
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: generate and test, Scala 2.13
        # This runs the template with the default parameters, and runs test within the templated app.
        run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test docs/paradox

      - name: generate and test, Scala 3
        run: |-
          sbt new file://$PWD --name=hello-world --scala_version=3.3.1 --force && pushd hello-world &&  sbt test