name: Build and test

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  build-test:
    runs-on: Akka-Default

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Docs
        run: sbt docs/paradox

      - name: generate and test, Scala 2.13
        # This runs the template with the default parameters, and runs test within the templated app.
        run: |-
          sbt new file://$PWD --name=hello-world --scala_version=2.13.18 --force && pushd hello-world && sbt test

      - name: generate and test, Scala 3
        run: |-
          sbt new file://$PWD --name=hello-world --scala_version=3.3.1 --force && pushd hello-world && sbt test